name: CD
on:
  push:
    branches:
      - main

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏷️ Get version from package.json
        run: |
          echo "REPOSITORY=techbridge-front" >> $GITHUB_ENV
          echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
          echo "PACKAGE_PATH=ghcr.io/techbridge-front" >> $GITHUB_ENV

      - name: 🏗️ Build Angular app
        run: npm run build-prod

      - name: ☁️ Upload build to AWS Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}
          port: 22 # SSH
          source: "dist/techbridge-front/*" 
          target: "/home/ubuntu/app/frontend-dist"
          strip_components: 3
